"""`merge_yaml/merged` must not ground an ingredient any way `normalized_yaml` doesn't (#267).

`data/merge_yaml/merged` is a derived product of `data/normalized_yaml`, but it is
tracked in git and is NOT regenerated by `just refresh-derived`. So a script that fixes
the corpus fixes only half of it, silently: validate-strict passes, the tests pass, the
fix looks complete, and the stale half keeps publishing the wrong id downstream.

That is not hypothetical. PR #257 corrected wrong-compound groundings against
`normalized_yaml` only. After it merged, `merge_yaml/merged` still had 608 files on
CHEBI:42758 (aldehydo-D-glucose) and 118 rows calling magnesium sulfate heptahydrate
potassium aluminium sulfate. #266 cleaned it up; this test is what stops it recurring.

Deliberately line-based rather than yaml.safe_load: parsing both corpora costs ~2m18s,
well past the slow-test budget, and this check only needs `preferred_term` and the id
under `term:`. The scan runs in a few seconds.
"""

from __future__ import annotations

import re
from collections import Counter, defaultdict
from pathlib import Path

import pytest

REPO = Path(__file__).resolve().parent.parent
NORMALIZED = REPO / "data" / "normalized_yaml"
MERGED = REPO / "data" / "merge_yaml" / "merged"

PREFERRED = re.compile(r"^\s*-?\s*preferred_term:\s*(.+?)\s*$")
BLOCK = re.compile(r"^(\s*)([A-Za-z_][A-Za-z0-9_]*):\s*$")
ID_LINE = re.compile(r"^\s*id:\s*(\S+)\s*$")


def _unquote(s: str) -> str:
    if len(s) >= 2 and s[0] == s[-1] and s[0] in "'\"":
        return s[1:-1].replace("''", "'") if s[0] == "'" else s[1:-1]
    return s


def groundings(root: Path) -> dict[str, Counter]:
    """ingredient name -> Counter of the `term.id`s it is grounded to under this root.

    Only ids directly under a `term:` block count. `mediaingredientmech_chebi_term`
    carries its own id and must not be conflated with the grounding.
    """
    out: dict[str, Counter] = defaultdict(Counter)
    for path in root.rglob("*.yaml"):
        try:
            text = path.read_text(errors="replace")
        except OSError:
            continue
        name, in_term = "", False
        for line in text.splitlines():
            m = PREFERRED.match(line)
            if m:
                name, in_term = _unquote(m.group(1)), False
                continue
            b = BLOCK.match(line)
            if b:
                in_term = b.group(2) == "term"
                continue
            if in_term:
                mi = ID_LINE.match(line)
                if mi and name:
                    out[name][mi.group(1)] += 1
                    in_term = False
    return out


@pytest.fixture(scope="module")
def both_corpora():
    if not MERGED.is_dir():
        pytest.skip("data/merge_yaml/merged is absent")
    return groundings(NORMALIZED), groundings(MERGED)


def test_merged_uses_no_grounding_absent_from_normalized(both_corpora):
    """Every (name, term.id) pair in the derived corpus must exist in the source one.

    Subset, NOT equality. The first version of this test compared the two corpora's
    modal grounding per name and failed on ~100 names that were never a drift problem:
    the roots hold different record populations — `normalized_yaml` carries solution
    records with a top-level `composition:` grounded to `mediadive.compound:` ids that
    `merged` does not — so a modal comparison measures population, not staleness.

    Subset is the invariant a derived corpus actually has to satisfy, and it is the one
    that catches the real failure: after #257 fixed `Glucose` in `normalized_yaml` only,
    `merged` still carried Glucose -> CHEBI:42758, an id no longer used for that name
    upstream. That is exactly a subset violation.
    """
    a, b = both_corpora
    stale = []
    for name, ids in b.items():
        upstream = set(a.get(name, ()))
        if not upstream:
            continue          # name absent upstream: a population difference, not drift
        for term_id, count in ids.items():
            if term_id not in upstream:
                stale.append(f"{name!r}: merged uses {term_id} ({count} rows), "
                             f"normalized uses {sorted(upstream)[:3]}")

    assert not stale, (
        f"{len(stale)} grounding(s) in data/merge_yaml/merged are not used for that "
        "ingredient anywhere in data/normalized_yaml (#267). merged is a DERIVED corpus, "
        "so this means a corpus fix ran against one root only — re-run it with "
        "`--yaml-dir data/merge_yaml/merged`:\n  " + "\n  ".join(stale[:20]))


def test_the_scan_actually_finds_groundings(both_corpora):
    """Guards the assertion above from passing vacuously if the parser stops matching."""
    a, b = both_corpora
    assert len(a) > 1000, f"only {len(a)} names found in normalized_yaml"
    assert len(b) > 1000, f"only {len(b)} names found in merge_yaml/merged"
    assert a.get("Glucose", Counter()).most_common(1)[0][0] == "CHEBI:17234"


def test_ids_under_the_mim_link_are_not_mistaken_for_groundings():
    """The two blocks are adjacent and shaped alike; conflating them would make this
    check report agreement it never verified."""
    import tempfile
    with tempfile.TemporaryDirectory() as td:
        p = Path(td) / "r.yaml"
        p.write_text(
            "ingredients:\n"
            "- preferred_term: Widget\n"
            "  term:\n"
            "    id: CHEBI:1\n"
            "    label: widget\n"
            "  mediaingredientmech_chebi_term:\n"
            "    id: CHEBI:999\n"
            "    label: widget\n"
        )
        g = groundings(Path(td))
    assert dict(g["Widget"]) == {"CHEBI:1": 1}


def test_the_subset_check_catches_a_stale_derived_corpus():
    """Proves the assertion above is not vacuous: reproduce #257's aftermath in
    miniature — the source fixed, the derived copy left on the retired id."""
    import tempfile
    with tempfile.TemporaryDirectory() as td:
        src, drv = Path(td) / "src", Path(td) / "drv"
        src.mkdir(); drv.mkdir()
        (src / "a.yaml").write_text(
            "ingredients:\n- preferred_term: Glucose\n  term:\n    id: CHEBI:17234\n")
        (drv / "a.yaml").write_text(
            "ingredients:\n- preferred_term: Glucose\n  term:\n    id: CHEBI:42758\n")
        a, b = groundings(src), groundings(drv)
    stale = [n for n, ids in b.items()
             for i in ids if a.get(n) and i not in set(a[n])]
    assert stale == ["Glucose"]
