"""The generated JSON schema must resolve (#367).

`culturemech.schema.json` is generated by `just gen-json-schema`, is tracked,
and is the artifact an external consumer validates against. On `main` it once
carried two `$ref`s to `#/$defs/Term` while `Term` was absent from `$defs` — so
against any validator that resolves references, the file did not load at all.

It was fixed incidentally, by the linkml 1.9.4 -> 1.11.1 bump in #365 changing
what the generator emits. Nothing asked for that fix and nothing would notice
it being undone: `gen-json-schema` runs in no workflow, so the file is only
regenerated when someone types the command, and the next generator change can
reintroduce a dangling reference silently.

These tests are the missing guard. They read the tracked file rather than
regenerating, because the tracked file is what consumers get.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import pytest

SCHEMA = (
    Path(__file__).resolve().parents[1]
    / "src"
    / "culturemech"
    / "schema"
    / "culturemech.schema.json"
)


@pytest.fixture(scope="module")
def schema() -> dict[str, Any]:
    assert SCHEMA.is_file(), f"{SCHEMA} is missing; run `just gen-json-schema`"
    return json.loads(SCHEMA.read_text())


def _refs(node: Any, path: str = "$") -> list[tuple[str, str]]:
    """Every ($ref value, json path) in the document, however deeply nested."""
    found: list[tuple[str, str]] = []
    if isinstance(node, dict):
        for key, value in node.items():
            if key == "$ref" and isinstance(value, str):
                found.append((value, path))
            else:
                found.extend(_refs(value, f"{path}.{key}"))
    elif isinstance(node, list):
        for index, value in enumerate(node):
            found.extend(_refs(value, f"{path}[{index}]"))
    return found


def test_every_local_ref_resolves_to_a_definition(schema):
    """The #367 defect: two `$ref`s to `#/$defs/Term`, no `Term` in `$defs`."""
    definitions = schema.get("$defs", {})
    dangling = sorted(
        {
            (ref, path)
            for ref, path in _refs(schema)
            if ref.startswith("#/$defs/") and ref.split("/")[-1] not in definitions
        }
    )
    assert not dangling, (
        f"{len(dangling)} $ref(s) name a definition that does not exist. "
        f"Regenerate with `just gen-json-schema`; if the generator still emits "
        f"them, that is an upstream linkml bug worth pinning. {dangling[:5]}"
    )


def test_the_guard_is_not_vacuous(schema):
    """A schema this size must actually contain local refs for the check to mean
    anything — a generator that stopped emitting `$ref` entirely would otherwise
    make the test above pass by finding nothing."""
    local = [ref for ref, _ in _refs(schema) if ref.startswith("#/$defs/")]
    assert len(local) > 50, f"only {len(local)} local $refs found; is this the right file?"
    assert len(schema.get("$defs", {})) > 50


def test_only_local_refs_are_used(schema):
    """A remote `$ref` would make validation require network access."""
    remote = sorted({ref for ref, _ in _refs(schema) if not ref.startswith("#")})
    assert not remote, f"schema references documents it does not ship: {remote}"


def test_the_schema_is_accepted_by_a_strict_validator(schema):
    """Resolution is necessary but not sufficient — this is the real contract.

    `check_schema` walks the document against the metaschema and raises on a
    structural problem, which is what an external consumer hits first.
    """
    jsonschema = pytest.importorskip("jsonschema")

    dialect = schema.get("$schema", "")
    validator = jsonschema.validators.validator_for(schema)
    assert validator is not None, f"no validator for dialect {dialect!r}"
    validator.check_schema(schema)


def test_the_root_still_describes_a_media_recipe(schema):
    """Cheap sanity that the tracked file is the schema it claims to be, so the
    checks above cannot pass against a truncated or half-written document."""
    assert schema.get("title")
    assert "MediaRecipe" in schema.get("$defs", {})
